# Generated by Django 3.1.5 on 2021-01-09 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_age', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('patient_address', models.CharField(max_length=250, null=True)),
                ('patient_phone', models.CharField(max_length=150, null=True)),
                ('patient_status', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
